## Remote package repositories
src/gz openwrt_core https://downloads.openwrt.org/releases/24.10.8/targets/x86/64/packages
src/gz openwrt_base https://downloads.openwrt.org/releases/24.10.8/packages/x86_64/base
src/gz openwrt_kmods https://downloads.openwrt.org/releases/24.10.8/targets/x86/64/kmods/6.6.144-1-50daf8372d971124fb3519e8d87e02ae
src/gz openwrt_luci https://downloads.openwrt.org/releases/24.10.8/packages/x86_64/luci
src/gz openwrt_packages https://downloads.openwrt.org/releases/24.10.8/packages/x86_64/packages
src/gz openwrt_routing https://downloads.openwrt.org/releases/24.10.8/packages/x86_64/routing
src/gz openwrt_telephony https://downloads.openwrt.org/releases/24.10.8/packages/x86_64/telephony


## This is the local package repository, do not remove!
src imagebuilder file:packages
option check_signature
